// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdbmPiN5t18Yt2EofZVSn6pfy20_vJ5fY',
    appId: '1:1056184209664:web:ef55ef3bc15f027fd023e5',
    messagingSenderId: '1056184209664',
    projectId: 'fir-class-b1551',
    authDomain: 'fir-class-b1551.firebaseapp.com',
    storageBucket: 'fir-class-b1551.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKcZkvYqKwFvPFAZbU1jBCxRzYrYRDOho',
    appId: '1:1056184209664:android:03ca3df3c1c05d0ad023e5',
    messagingSenderId: '1056184209664',
    projectId: 'fir-class-b1551',
    storageBucket: 'fir-class-b1551.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNkCnTV0D9yVajG3Es8GFKoUzbZCeEQnM',
    appId: '1:1056184209664:ios:bda8e217dbc5b8d6d023e5',
    messagingSenderId: '1056184209664',
    projectId: 'fir-class-b1551',
    storageBucket: 'fir-class-b1551.appspot.com',
    iosBundleId: 'com.example.firebaseclass1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNkCnTV0D9yVajG3Es8GFKoUzbZCeEQnM',
    appId: '1:1056184209664:ios:bda8e217dbc5b8d6d023e5',
    messagingSenderId: '1056184209664',
    projectId: 'fir-class-b1551',
    storageBucket: 'fir-class-b1551.appspot.com',
    iosBundleId: 'com.example.firebaseclass1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCdbmPiN5t18Yt2EofZVSn6pfy20_vJ5fY',
    appId: '1:1056184209664:web:8c267531e4ac54b5d023e5',
    messagingSenderId: '1056184209664',
    projectId: 'fir-class-b1551',
    authDomain: 'fir-class-b1551.firebaseapp.com',
    storageBucket: 'fir-class-b1551.appspot.com',
  );
}
